# This workflow will build a golang project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-go

name: Go

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:

  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3

    - name: Set up Go
      uses: actions/setup-go@v4
      with:
        go-version: '1.22'

    - name: Build
      run: |
        cd linebot &&
        go build -v ./...

    - name: Test
      run: |
        cd linebot &&
        mkdir coverage;
        go test -v -cover ./... -coverprofile=coverage/cover.out && go tool cover -html coverage/cover.out -o coverage/cover.html
    - name: Upload Test Result
      uses: actions/upload-artifact@v4
      with:
        name: test-coverage
        path: linebot/coverage/cover.html
